CREATE SCHEMA IF NOT EXISTS auth;
CREATE USER gotrue WITH PASSWORD 'gotrue_password';
GRANT ALL PRIVILEGES ON SCHEMA auth TO gotrue;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA auth TO gotrue;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA auth TO gotrue;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON TABLES TO gotrue;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON SEQUENCES TO gotrue;
ALTER ROLE gotrue SET search_path TO auth;

-- Схема и пользователь для api
CREATE SCHEMA IF NOT EXISTS app;
CREATE USER app WITH PASSWORD 'app_password';
GRANT ALL PRIVILEGES ON SCHEMA app TO app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA app TO app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA app TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT ALL ON TABLES TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT ALL ON SEQUENCES TO app;
ALTER ROLE app SET search_path TO app, public;
