os_name: ~
file_system: ~
docker_mode: root
services_restart_policy: always

projects:
 - name: studio
   src: git@github.com:resoul/studio.git
 - name: api
   src: git@github.com:resoul/api.git

enabled_services:
  - adminer
  - db
  - mailpit
  - auth
  - api
  - studio
